# TEMPLATE: Copy this file for each booking date
# 1. Copy to: .github/workflows/book-YYYY-MM-DD.yml  
# 2. Change: name, cron schedule, and target date
# 3. Commit and push

name: Book YYYY-MM-DD

on:
  schedule:
    # Calculate: target_date - 2 days at 17:01 UTC (18:01 Netherlands)
    # Format: 'minute hour day month weekday'
    - cron: 'CHANGE_ME'
  
  workflow_dispatch:

jobs:
  reserve:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create .env file
      env:
        EMAIL: ${{ secrets.EMAIL }}
        LOCATION: ${{ secrets.LOCATION }}
        TYPE: ${{ secrets.TYPE }}
        BASE_EMAIL: ${{ secrets.BASE_EMAIL }}
        ENGINE_BODY: ${{ secrets.ENGINE_BODY }}
      run: |
        cat > .env << EOF
        EMAIL=${{ secrets.EMAIL }}
        LOCATION=${{ secrets.LOCATION }}
        TYPE=${{ secrets.TYPE }}
        BASE_EMAIL=${{ secrets.BASE_EMAIL }}
        ENGINE_BODY=${{ secrets.ENGINE_BODY }}
        EOF
        
    - name: Book target date
      run: |
        echo "🎯 Booking YYYY-MM-DD at optimal time"
        echo "📅 Perfect timing - booking window just opened!"
        node reserve.mjs --date "YYYY-MM-DD" --start "09:00" --end "17:00" --resource "565"