# TEMPLATE: Copy this file and customize for each booking
# Example: .github/workflows/book-2025-08-11.yml

name: Book 2025-08-11

on:
  schedule:
    # Run on 2025-08-09 at 17:01 UTC (18:01 Netherlands)
    # Cron format: minute hour day month weekday
    - cron: '1 17 9 8 *'
  
  # Manual trigger for testing
  workflow_dispatch:

jobs:
  reserve:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create .env file
      env:
        EMAIL: ${{ secrets.EMAIL }}
        LOCATION: ${{ secrets.LOCATION }}
        TYPE: ${{ secrets.TYPE }}
        BASE_EMAIL: ${{ secrets.BASE_EMAIL }}
        ENGINE_BODY: ${{ secrets.ENGINE_BODY }}
      run: |
        cat > .env << EOF
        EMAIL=${{ secrets.EMAIL }}
        LOCATION=${{ secrets.LOCATION }}
        TYPE=${{ secrets.TYPE }}
        BASE_EMAIL=${{ secrets.BASE_EMAIL }}
        ENGINE_BODY=${{ secrets.ENGINE_BODY }}
        EOF
        
    - name: Book specific date
      run: |
        echo "🎯 Booking 2025-08-11 at optimal time (18:01 Netherlands)"
        echo "📅 Perfect timing - booking window just opened!"
        node reserve.mjs --date "2025-08-11" --start "09:00" --end "17:00" --resource "565"

# TO USE THIS TEMPLATE:
# 1. Copy to .github/workflows/book-YYYY-MM-DD.yml
# 2. Change the name and date references
# 3. Calculate cron: target_date - 2 days at 17:01 UTC
# 4. Commit and push

# CRON EXAMPLES:
# Book 2025-08-11 → Schedule 2025-08-09 → '1 17 9 8 *'
# Book 2025-08-12 → Schedule 2025-08-10 → '1 17 10 8 *'  
# Book 2025-08-15 → Schedule 2025-08-13 → '1 17 13 8 *'